name: dm4bem-env

channels:
  - conda-forge

dependencies:
  - python=3.8.8
  - jupyter=1.0.0
  - jupyterlab=3.0.14
  - ipywidgets=8.0.4
  - matplotlib=3.4.1
  - numpy=1.20.2
  - scipy=1.6.2
  - pandas=1.2.4
  - voila=0.2.11
  - ipympl=0.9.3
